config/routes.rb
Elabs::Engine.routes.draw do
  # Devise routes: use Elabs custom controllers (adds support for username and preferences)
  devise_for :users, path: 'auth', controllers: {
    confirmations: 'elabs/auth/confirmations',
    passwords:     'elabs/auth/passwords',
    registrations: 'elabs/auth/registrations',
    sessions:      'elabs/auth/sessions',
    unlocks:       'elabs/auth/unlocks'
  }
  # Resources
  resources :albums,    only: %i[index show], param: :slug do
    resources :uploads, only: %i[index]
    post 'comment', to: 'albums#create_comment', as: 'create_comment', param: :slug
  end
  resources :articles,  only: %i[index show], param: :slug do
    post 'comment', to: 'articles#create_comment', as: 'create_comment', param: :slug
  end
  resources :notes, only: %i[index show], param: :slug do
    post 'comment', to: 'notes#create_comment', as: 'create_comment', param: :slug
  end
  resources :projects, only: %i[index show], param: :slug do
    resources :articles, only: %i[index]
    resources :albums,   only: %i[index]
    resources :notes,    only: %i[index]
    resources :uploads,  only: %i[index]
    post 'comment', to: 'projects#create_comment', as: 'create_comment', param: :slug
  end
  resources :uploads, only: %i[index show], param: :slug do
    post 'comment', to: 'uploads#create_comment', as: 'create_comment', param: :slug
  end
  resources :links, only: %i[index]

  # Classifiers
  resources :languages, only: %i[index show], param: :iso639_1 do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :links,    only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :licenses, only: %i[index show], param: :slug do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :tags, only: %i[index show], param: :slug do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :links,    only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :users, only: %i[index show], param: :username do
    resources :albums,   only: %i[index]
    resources :links,    only: %i[index]
    resources :articles, only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end

  # Reports
  post '/reports', to: 'reports#create', as: :create_report

  # Activity
  get '/activity', to: 'acts#index', as: :activities

  # Member
  namespace :member do
    resources :albums, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'albums#toggle_publication', as: :toggle_publication
    end
    resources :articles, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'articles#toggle_publication', as: :toggle_publication
    end
    resources :links, except: %i[show] do
      put 'toggle_publication', to: 'links#toggle_publication', as: :toggle_publication
    end
    resources :notes, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'notes#toggle_publication', as: :toggle_publication
    end
    resources :projects, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'projects#toggle_publication', as: :toggle_publication
    end
    resources :uploads, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'uploads#toggle_publication', as: :toggle_publication
    end

    resources :notifications, only: %i[index destroy]

    resources :comments, only: %i[destroy] do
      put '/archive', to: 'comments#archive', as: :archive
    end

    get '/preferences', to: 'preferences#edit', as: :edit_preferences
    put '/preferences', to: 'preferences#update', as: :update_preferences

    get '/infos', to: 'users#edit', as: :edit_infos
    put '/infos', to: 'users#update', as: :update_infos

    post '/markdown_previewer', to: 'markdown_previewer#preview', as: :markdown_preview
  end

  # Admin
  namespace :admin do
    # Content resources
    resources :albums, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'albums#toggle_lock', as: :toggle_lock
    end
    resources :articles, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'articles#toggle_lock', as: :toggle_lock
    end
    resources :links, only: %i[index destroy] do
      put 'toggle_lock', to: 'links#toggle_lock', as: :toggle_lock
    end
    resources :notes, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'notes#toggle_lock', as: :toggle_lock
    end
    resources :projects, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'projects#toggle_lock', as: :toggle_lock
    end
    resources :uploads, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'uploads#toggle_lock', as: :toggle_lock
    end

    # Basic resources
    resources :announcements, except: %i[show]
    resources :languages,     except: %i[show], param: :iso639_1
    resources :licenses,      except: %i[show], param: :slug
    resources :reports,       only:   %i[index destroy]
    resources :tags,          except: %i[create show], param: :slug
    resources :users,         only:   %i[index show destroy], param: :username
  end
end

app/models/elabs/act.rb
module Elabs
  class Act < ApplicationRecord
    self.table_name = 'acts'

    belongs_to :content, polymorphic: true
  end
end

app/models/elabs/album.rb
module Elabs
  class Album < ApplicationContentRecord
    self.table_name = 'albums'

    SLUGGABLE_FIELD = :name
    COUNTER_CACHES = [
      %w[projects albums],
      %w[tags albums],
      'license',
      'language',
      'user'
    ].freeze

    validates :name,        presence: true
    validates :description, presence: true
    validates :slug,        presence: true, uniqueness: true
    validates_with AssociatedAuthorValidator, relations: %w[project upload]

    belongs_to :user
    belongs_to :license
    belongs_to :language
    has_many :albums_tags # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :projects_albums # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :albums_uploads # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :tags,     through: :albums_tags,     dependent: :destroy
    has_many :projects, through: :projects_albums, dependent: :destroy
    has_many :uploads,  through: :albums_uploads,  dependent: :destroy
    has_many :comments, as: 'content', dependent: :destroy
    # Public filters
    has_many :public_projects, -> { publicly_visible }, through: :projects_albums, source: :project
    has_many :public_uploads,  -> { publicly_visible }, through: :albums_uploads,  source: :upload

    scope :for_list, -> { order(:name).pluck(:name, :id) }

    def title_to_display
      name
    end

    def short_text_to_display
      nil
    end

    def long_text_to_display
      description
    end
  end
end

app/models/elabs/albums_tag.rb
module Elabs
  class AlbumsTag < ApplicationRecord
    self.table_name = 'albums_tags'

    include Elabs::Concerns::CountablePivot
    COUNTABLE_DEFINITION = %i[albums tag].freeze

    belongs_to :album
    belongs_to :tag
  end
end

app/models/elabs/albums_upload.rb
module Elabs
  class AlbumsUpload < ApplicationRecord
    self.table_name = 'albums_uploads'

    include Elabs::Concerns::CountablePivot

    COUNTABLE_DEFINITION = %i[uploads album].freeze

    belongs_to :album
    belongs_to :upload
  end
end

app/models/elabs/announcement.rb
module Elabs
  class Announcement < ApplicationRecord
    self.table_name = 'announcements'

    validates :level, inclusion: { in: %w[info warning danger] }, presence: true
    validates :target, inclusion: { in: %w[global public member admin] }, presence: true
    validates :content, presence: true

    before_save :clean_dates

    belongs_to :user

    scope :visible, lambda {
      now = Time.current
      where('start_at <= ? OR start_at IS NULL', now).where('end_at >= ? OR end_at IS NULL', now)
    }

    def self.for_user(user)
      return visible.where('target = ? OR target = ?', :global, :member) if user&.role == 'user'

      return visible.where('target = ? OR target = ? OR target = ?', :global, :member, :admin) if user&.role == 'admin'

      visible.where(target: :global)
    end

    private

    def clean_dates
      self.start_at = nil if start_at == ''
      self.end_at   = nil if end_at == ''
    end
  end
end

app/models/elabs/application_content_record.rb
module Elabs
  class ApplicationContentRecord < ApplicationRecord
    include Elabs::Concerns::ContentEntity
    include Elabs::Concerns::ActableEntity
    include Elabs::Concerns::CountableEntity
    include Elabs::Concerns::NotifiableEntity
    include Elabs::Concerns::Taggable
    include Elabs::Concerns::Sluggable

    SLUG_FIELD  = :slug
    ACT_UPDATES = true

    self.abstract_class = true
  end
end

app/models/elabs/application_record.rb
module Elabs
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    attr_accessor :changed_by

    def self.find_by_slug_or_id(params)
      if sluggable?
        slug = params[:slug] || params["#{table_name.classify.downcase}_slug"]
        return find_by!(slug: slug)
      end

      find(params[:id] || params["#{table_name.classify.downcase}_id"])
    end

    def self.sluggable?
      const_defined?('SLUG_FIELD') && !self::SLUG_FIELD.nil?
    end
  end
end

app/models/elabs/article.rb
module Elabs
  class Article < ApplicationContentRecord
    self.table_name = 'articles'

    SLUGGABLE_FIELD = :title
    COUNTER_CACHES = [
      %w[projects articles],
      %w[tags articles],
      'license',
      'language',
      'user'
    ].freeze

    validates :title,   presence: true
    validates :excerpt, presence: true
    validates :content, presence: true
    validates :slug,    presence: true, uniqueness: true
    validates_with AssociatedAuthorValidator, relations: %w[project]

    belongs_to :user
    belongs_to :license
    belongs_to :language
    has_many :articles_tags # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :projects_articles # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :tags,     through: :articles_tags,     dependent: :destroy
    has_many :projects, through: :projects_articles, dependent: :destroy
    has_many :comments, as: 'content', dependent: :destroy
    # Public filters
    has_many :public_projects, -> { publicly_visible }, through: :projects_articles, source: :project

    def title_to_display
      title
    end

    def short_text_to_display
      excerpt
    end

    def long_text_to_display
      content
    end
  end
end

app/models/elabs/articles_tag.rb
module Elabs
  class ArticlesTag < ApplicationRecord
    self.table_name = 'articles_tags'

    include Elabs::Concerns::CountablePivot

    COUNTABLE_DEFINITION = %i[articles tag].freeze

    belongs_to :article
    belongs_to :tag
  end
end

app/models/elabs/comment.rb
module Elabs
  class Comment < ApplicationRecord
    self.table_name = 'comments'

    validates :comment, presence: true
    validates :user,    presence: true, unless: :name
    validates :name,    presence: true, unless: :user

    belongs_to :content,       polymorphic: true
    belongs_to :user,          optional: true
    has_many   :notifications, as: :content, dependent: :destroy

    after_create :notify_author, if: :notify_author?

    def username
      user_id ? user.display_name : name
    end

    def notify_author?
      user_id ? content.user_id != user_id : true
    end

    def notify_author
      notification = { content: self,
                       event:   :comment,
                       user_id: content.user_id }
      notification[:source_user] = user if user_id
      Elabs::Notification.create! notification
    end

    def archive!
      update(archived: true)
      notifications.destroy_all
    end
  end
end

app/models/elabs/concerns/actable_entity.rb
module Elabs
  module Concerns
    module ActableEntity
      extend ActiveSupport::Concern

      included do
        attr_accessor :update_description
        attr_reader :minor_update

        has_many :acts, as: :content, dependent: :destroy

        before_save :update_acts?
        after_save :update_acts
      end

      def minor_update=(value)
        @minor_update = ['t', '1', 1, true].include? value
      end

      def minor_update?
        @minor_update || false
      end

      private

      def update_acts? # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
        @action = if minor_update?
                    :nothing
                  elsif just_published?
                    current_publish_action
                  elsif made_locked? && act_updates?
                    current_lock_action
                  elsif notably_changed? && act_updates?
                    current_update_action
                  else
                    :nothing
                  end
      end

      def update_acts
        acts.destroy_all if %i[lock unpublish].include? @action
        reason = update_description.nil? ? nil : update_description
        Act.create content: self, event: @action, reason: reason unless @action == :nothing || hidden_in_history
      end

      # Whether or not to save the update acts for the current model
      def act_updates?
        self.class::ACT_UPDATES
      end

      def made_locked?
        changed.include?('locked') && published?
      end

      def notably_changed?
        (changed & %w[title name description short_description content excerpt]).any?
      end

      def just_published?
        changed.include?('published')
      end
    end
  end
end

app/models/elabs/concerns/content_entity.rb
module Elabs
  module Concerns
    module ContentEntity
      extend ActiveSupport::Concern

      included do
        before_save :set_publication_date

        scope :by_member,        ->(user_id) { where(user_id: user_id) }
        scope :published,        -> { where(published: true) }
        scope :unlocked,         -> { where(locked: false) }
        scope :publicly_visible, -> { published.unlocked }
        scope :for_relation,     -> { publicly_visible.order(published_at: 'desc').limit(Elabs.max_related_items) }
      end

      def locked?
        locked
      end

      def unlocked?
        !locked
      end

      def draft?
        !published
      end

      def published?
        published
      end

      def publicly_visible?
        published? && !locked?
      end

      def not_publicly_visible?
        draft? || locked?
      end

      private

      def made_publicly_visible?
        (changes_include?(:published) || changes_include?(:locked)) && published? && unlocked?
      end

      def made_publicly_invisible?
        (changes_include?(:published) && draft?) || (changes_include?(:locked) && locked? && published?)
      end

      def was_published_before?
        (changes_include?(:published) && draft?)
      end

      def set_publication_date
        self.published_at = Time.current if changed.include?('published') && published?
        self.published_at = nil if changed.include?('published') && !published?
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_publish_action
        return :nothing unless unlocked?

        published? ? :publish : :unpublish
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_lock_action
        return :nothing unless published?

        locked? ? :lock : :unlock
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_update_action
        published? && unlocked? ? :update : :nothing
      end

      def changed_by_someone_else
        changed_by.present? && changed_by.id != user.id
      end

      class_methods do
        def find_publicly_visible(slug)
          entity = where(slug: slug).published.first

          raise ActiveRecord::RecordNotFound if entity.nil?

          entity
        end
      end
    end
  end
end

app/models/elabs/concerns/countable_pivot.rb
module Elabs
  module Concerns
    module CountablePivot
      extend ActiveSupport::Concern

      # List of tables to query for update
      COUNTABLE_DEFINITION = [].freeze

      included do
        before_destroy :update_associated_counter_cache
      end

      # rubocop:disable Rails/SkipsModelValidations
      # We don't want any hook to be called
      def update_associated_counter_cache
        entity = send(self.class::COUNTABLE_DEFINITION[1])
        entity.decrement! "#{self.class::COUNTABLE_DEFINITION[0]}_count"
      end
      # rubocop:enable Rails/SkipsModelValidations
    end
  end
end

app/models/elabs/concerns/taggable.rb
module Elabs
  module Concerns
    module Taggable
      extend ActiveSupport::Concern

      included do
        attr_writer :tags_list

        after_save :save_tags_list
      end

      def save_tags_list
        if @tags_list
          tags = []
          @tags_list.split(/, */).each do |t|
            tags.push Tag.find_or_create_by(name: t.chomp)
          end

          @tags_list = nil

          update(tags: tags) if tags.count.positive?
        end

        true
      end

      # Returns a list of comma-separated tags
      def tags_list
        @tags_list || tags.map(&:name).join(', ')
      end
    end
  end
end

app/views/elabs/projects/_filters.html.haml
.page__header__actions__filters
  .page__header__actions__filters__group
    .page__header__actions__filters__group__title= t('.sort_by')
    = order_link t('.name'), 'name'
    = order_link t('.pub_date'), 'published_at'
    = order_link t('.upd_date'), 'updated_at'

  .page__header__actions__filters__group
    .page__header__actions__filters__group__title= t('.nsfw_content')
    = sfw_status_links

app/views/elabs/projects/_project_inline.html.haml
- if !show_item? project
  = render 'elabs/layouts/hidden_entry_inline', entity: project
- else
  %span.project.project--inline
    = icon 'cog', ['fw']
    = link_to project.name, project, lang: project.language.iso639_1
    - if project.language.iso639_1 != locale
      (#{project.language.iso639_1})

app/views/elabs/projects/index.html.haml
- @page_title = t('.projects')

.projects-list
  = render 'elabs/layouts/empty' if @projects.length.zero?

  - @projects.each do |p|
    = render 'elabs/layouts/content_card', entity: p

= paginate @projects

app/views/elabs/projects/show.html.haml
- if !show_item? @project
  - @page_title = t('.content_not_displayed')
  = render 'elabs/layouts/hidden_entry_full', entity: @project
- else
  - @page_title = @project.name
  .project.project--full
    %aside.header
      %ul
        - if @project.main_url.present?
          %li
            = icon('home', ['fw'])
            %strong= link_to t('.home_page'), @project.main_url, target: '_blank', rel: 'noopener noreferrer'
        - else
          %li{ disabled: true }
            = icon_text('home', t('.home_page'), ['fw'])

        - if @project.sources_url.present?
          %li
            = icon('code', ['fw'])
            %strong= link_to t('.sources'), @project.sources_url, target: '_blank', rel: 'noopener noreferrer'
        - else
          %li{ disabled: true }
            = icon_text('code', t('.sources'), ['fw'])

        - if @project.docs_url.present?
          %li
            = icon('book', ['fw'])
            %strong= link_to t('.documentation'), @project.docs_url, target: '_blank', rel: 'noopener noreferrer'
        - else
          %li{ disabled: true }
            = icon_text('book', t('.documentation'), ['fw'])

    %aside.details
      %ul
        %li.separator
          %ul
            %li.detail
              = icon('user', ['fw'])
              %strong= t('.author')
              = link_to @project.user.display_name, @project.user
            %li.detail
              = icon('calendar-check', ['fw'])
              %strong= t('.published_at')
              = medium_datetime @project.published_at
            %li.detail
              = icon('calendar', ['fw'])
              %strong= t('.updated_at')
              = medium_datetime @project.updated_at

        %li.separator
          %ul
            %li.detail
              = icon('info', ['fw'])
              %strong= t('.sfw')
              = boolean_icon_tag @project.sfw, 'is-sfw', 'is-nsfw'
            %li.detail
              = icon('license', ['fw'])
              %strong= t('.license')
              = link_to @project.license do
                = license_icon @project.license
                = @project.license.name
            %li.detail
              = icon('language', ['fw'])
              %strong= t('.language')
              = link_to @project.language.name, @project.language

          %li.separator
            %ul
              %li.detail
                = icon('amount', ['fw'])
                %strong= t('.albums_count')
                = @project.albums_count
              %li.detail
                = icon('amount', ['fw'])
                %strong= t('.articles_count')
                = @project.articles_count
              %li.detail
                = icon('amount', ['fw'])
                %strong= t('.notes_count')
                = @project.notes_count
              %li.detail
                = icon('amount', ['fw'])
                %strong= t('.uploads_count')
                = @project.uploads_count
              %li.separator.detail= render 'elabs/layouts/content_classifiers_lists/tags', tags: @project.tags

          = render 'elabs/layouts/content_download_sources', entity: @note

    .content
      %article{ lang: @project.language.iso639_1 }
        = render_entity_content @project, :short_description
        = render_entity_content @project, :description

      = render 'elabs/layouts/content_associations', is_section: true, entity: @project

  = render 'elabs/comments/comments',
            entity: @project,
            new_comment: @new_comment,
            url: project_create_comment_path(@project)

app/views/elabs/projects/show.md.erb
<%
title            = t('.title', type: t('.project'), title: @project.name)
username         = @project.user.display_name
publication_date = @project.published_at
has_update       = @project.published_at < @project.updated_at

if params[:md_format] == 'pandoc' %>
% <%= title %>
% <%= username %>
% <%= publication_date %>

<% else %>
# <%= title %>

- **<%= t('.author') %>** <%= username %>
- **<%= t('.published_at') %>** <%= publication_date %>
<% end %>
<% if has_update %>
- **<%= t('.updated_at') %>** <%= @project.updated_at %>
<% end %>
- **<%= t('.language') %>** <%= @project.language.name %>
- **<%= t('.license') %>** [<%= @project.license.name %>](<%= @project.license.url %>)
- **<%= t('.tags') %>** <% @project.tags.each do |tag| %><%= tag.name %>, <% end %>
- **<%= t('.original_url') %>** <%= project_url(@project) %>
- **<%= t('.sfw') %>** <%= @project.sfw ? t('yes') : t('no') %>

---

<%= @project.description %>

## <%= t('.associated_content') %>
<% if @project.albums_count > 0 %>

### <%= t('.albums') %>

<% @project.albums.each do |album| %>
- [<%= album.name %>](<%= album_url(album) %>)
<% end %>
<% end %>
<% if @project.articles_count > 0 %>

### <%= t('.articles') %>

<% @project.articles.each do |article| %>
- [<%= article.title %>](<%= article_url(article) %>)
<% end %>
<% end %>
<% if @project.notes_count > 0 %>

### <%= t('.notes') %>

<% @project.notes.each do |note| %>
- [<%= note.published_at %>](<%= note_url(note) %>)
<% end %>
<% end %>
<% if @project.uploads_count > 0 %>

### <%= t('.files') %>

<% @project.uploads.each do |upload| %>
- [<%= upload.title %>](<%= upload_url(upload) %>)
<% end %>
<% end %>