config/routes.rb
Elabs::Engine.routes.draw do
  # Devise routes: use Elabs custom controllers (adds support for username and preferences)
  devise_for :users, path: 'auth', controllers: {
    confirmations: 'elabs/auth/confirmations',
    passwords:     'elabs/auth/passwords',
    registrations: 'elabs/auth/registrations',
    sessions:      'elabs/auth/sessions',
    unlocks:       'elabs/auth/unlocks'
  }
  # Resources
  resources :albums,    only: %i[index show], param: :slug do
    resources :uploads, only: %i[index]
    post 'comment', to: 'albums#create_comment', as: 'create_comment', param: :slug
  end
  resources :articles,  only: %i[index show], param: :slug do
    post 'comment', to: 'articles#create_comment', as: 'create_comment', param: :slug
  end
  resources :notes, only: %i[index show], param: :slug do
    post 'comment', to: 'notes#create_comment', as: 'create_comment', param: :slug
  end
  resources :projects, only: %i[index show], param: :slug do
    resources :articles, only: %i[index]
    resources :albums,   only: %i[index]
    resources :notes,    only: %i[index]
    resources :uploads,  only: %i[index]
    post 'comment', to: 'projects#create_comment', as: 'create_comment', param: :slug
  end
  resources :uploads, only: %i[index show], param: :slug do
    post 'comment', to: 'uploads#create_comment', as: 'create_comment', param: :slug
  end
  resources :links, only: %i[index]

  # Classifiers
  resources :languages, only: %i[index show], param: :iso639_1 do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :links,    only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :licenses, only: %i[index show], param: :slug do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :tags, only: %i[index show], param: :slug do
    resources :albums,   only: %i[index]
    resources :articles, only: %i[index]
    resources :links,    only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end
  resources :users, only: %i[index show], param: :username do
    resources :albums,   only: %i[index]
    resources :links,    only: %i[index]
    resources :articles, only: %i[index]
    resources :notes,    only: %i[index]
    resources :projects, only: %i[index]
    resources :uploads,  only: %i[index]
  end

  # Reports
  post '/reports', to: 'reports#create', as: :create_report

  # Activity
  get '/activity', to: 'acts#index', as: :activities

  # Member
  namespace :member do
    resources :albums, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'albums#toggle_publication', as: :toggle_publication
    end
    resources :articles, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'articles#toggle_publication', as: :toggle_publication
    end
    resources :links, except: %i[show] do
      put 'toggle_publication', to: 'links#toggle_publication', as: :toggle_publication
    end
    resources :notes, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'notes#toggle_publication', as: :toggle_publication
    end
    resources :projects, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'projects#toggle_publication', as: :toggle_publication
    end
    resources :uploads, except: %i[show], param: :slug do
      put 'toggle_publication', to: 'uploads#toggle_publication', as: :toggle_publication
    end

    resources :notifications, only: %i[index destroy]

    resources :comments, only: %i[destroy] do
      put '/archive', to: 'comments#archive', as: :archive
    end

    get '/preferences', to: 'preferences#edit', as: :edit_preferences
    put '/preferences', to: 'preferences#update', as: :update_preferences

    get '/infos', to: 'users#edit', as: :edit_infos
    put '/infos', to: 'users#update', as: :update_infos

    post '/markdown_previewer', to: 'markdown_previewer#preview', as: :markdown_preview
  end

  # Admin
  namespace :admin do
    # Content resources
    resources :albums, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'albums#toggle_lock', as: :toggle_lock
    end
    resources :articles, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'articles#toggle_lock', as: :toggle_lock
    end
    resources :links, only: %i[index destroy] do
      put 'toggle_lock', to: 'links#toggle_lock', as: :toggle_lock
    end
    resources :notes, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'notes#toggle_lock', as: :toggle_lock
    end
    resources :projects, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'projects#toggle_lock', as: :toggle_lock
    end
    resources :uploads, only: %i[index destroy], param: :slug do
      put 'toggle_lock', to: 'uploads#toggle_lock', as: :toggle_lock
    end

    # Basic resources
    resources :announcements, except: %i[show]
    resources :languages,     except: %i[show], param: :iso639_1
    resources :licenses,      except: %i[show], param: :slug
    resources :reports,       only:   %i[index destroy]
    resources :tags,          except: %i[create show], param: :slug
    resources :users,         only:   %i[index show destroy], param: :username
  end
end

app/models/elabs/act.rb
module Elabs
  class Act < ApplicationRecord
    self.table_name = 'acts'

    belongs_to :content, polymorphic: true
  end
end

app/models/elabs/album.rb
module Elabs
  class Album < ApplicationContentRecord
    self.table_name = 'albums'

    SLUGGABLE_FIELD = :name
    COUNTER_CACHES = [
      %w[projects albums],
      %w[tags albums],
      'license',
      'language',
      'user'
    ].freeze

    validates :name,        presence: true
    validates :description, presence: true
    validates :slug,        presence: true, uniqueness: true
    validates_with AssociatedAuthorValidator, relations: %w[project upload]

    belongs_to :user
    belongs_to :license
    belongs_to :language
    has_many :albums_tags # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :projects_albums # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :albums_uploads # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :tags,     through: :albums_tags,     dependent: :destroy
    has_many :projects, through: :projects_albums, dependent: :destroy
    has_many :uploads,  through: :albums_uploads,  dependent: :destroy
    has_many :comments, as: 'content', dependent: :destroy
    # Public filters
    has_many :public_projects, -> { publicly_visible }, through: :projects_albums, source: :project
    has_many :public_uploads,  -> { publicly_visible }, through: :albums_uploads,  source: :upload

    scope :for_list, -> { order(:name).pluck(:name, :id) }

    def title_to_display
      name
    end

    def short_text_to_display
      nil
    end

    def long_text_to_display
      description
    end
  end
end

app/models/elabs/albums_tag.rb
module Elabs
  class AlbumsTag < ApplicationRecord
    self.table_name = 'albums_tags'

    include Elabs::Concerns::CountablePivot
    COUNTABLE_DEFINITION = %i[albums tag].freeze

    belongs_to :album
    belongs_to :tag
  end
end

app/models/elabs/albums_upload.rb
module Elabs
  class AlbumsUpload < ApplicationRecord
    self.table_name = 'albums_uploads'

    include Elabs::Concerns::CountablePivot

    COUNTABLE_DEFINITION = %i[uploads album].freeze

    belongs_to :album
    belongs_to :upload
  end
end

app/models/elabs/announcement.rb
module Elabs
  class Announcement < ApplicationRecord
    self.table_name = 'announcements'

    validates :level, inclusion: { in: %w[info warning danger] }, presence: true
    validates :target, inclusion: { in: %w[global public member admin] }, presence: true
    validates :content, presence: true

    before_save :clean_dates

    belongs_to :user

    scope :visible, lambda {
      now = Time.current
      where('start_at <= ? OR start_at IS NULL', now).where('end_at >= ? OR end_at IS NULL', now)
    }

    def self.for_user(user)
      return visible.where('target = ? OR target = ?', :global, :member) if user&.role == 'user'

      return visible.where('target = ? OR target = ? OR target = ?', :global, :member, :admin) if user&.role == 'admin'

      visible.where(target: :global)
    end

    private

    def clean_dates
      self.start_at = nil if start_at == ''
      self.end_at   = nil if end_at == ''
    end
  end
end

app/models/elabs/application_content_record.rb
module Elabs
  class ApplicationContentRecord < ApplicationRecord
    include Elabs::Concerns::ContentEntity
    include Elabs::Concerns::ActableEntity
    include Elabs::Concerns::CountableEntity
    include Elabs::Concerns::NotifiableEntity
    include Elabs::Concerns::Taggable
    include Elabs::Concerns::Sluggable

    SLUG_FIELD  = :slug
    ACT_UPDATES = true

    self.abstract_class = true
  end
end

app/models/elabs/application_record.rb
module Elabs
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    attr_accessor :changed_by

    def self.find_by_slug_or_id(params)
      if sluggable?
        slug = params[:slug] || params["#{table_name.classify.downcase}_slug"]
        return find_by!(slug: slug)
      end

      find(params[:id] || params["#{table_name.classify.downcase}_id"])
    end

    def self.sluggable?
      const_defined?('SLUG_FIELD') && !self::SLUG_FIELD.nil?
    end
  end
end

app/models/elabs/article.rb
module Elabs
  class Article < ApplicationContentRecord
    self.table_name = 'articles'

    SLUGGABLE_FIELD = :title
    COUNTER_CACHES = [
      %w[projects articles],
      %w[tags articles],
      'license',
      'language',
      'user'
    ].freeze

    validates :title,   presence: true
    validates :excerpt, presence: true
    validates :content, presence: true
    validates :slug,    presence: true, uniqueness: true
    validates_with AssociatedAuthorValidator, relations: %w[project]

    belongs_to :user
    belongs_to :license
    belongs_to :language
    has_many :articles_tags # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :projects_articles # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :tags,     through: :articles_tags,     dependent: :destroy
    has_many :projects, through: :projects_articles, dependent: :destroy
    has_many :comments, as: 'content', dependent: :destroy
    # Public filters
    has_many :public_projects, -> { publicly_visible }, through: :projects_articles, source: :project

    def title_to_display
      title
    end

    def short_text_to_display
      excerpt
    end

    def long_text_to_display
      content
    end
  end
end

app/models/elabs/articles_tag.rb
module Elabs
  class ArticlesTag < ApplicationRecord
    self.table_name = 'articles_tags'

    include Elabs::Concerns::CountablePivot

    COUNTABLE_DEFINITION = %i[articles tag].freeze

    belongs_to :article
    belongs_to :tag
  end
end

app/models/elabs/comment.rb
module Elabs
  class Comment < ApplicationRecord
    self.table_name = 'comments'

    validates :comment, presence: true
    validates :user,    presence: true, unless: :name
    validates :name,    presence: true, unless: :user

    belongs_to :content,       polymorphic: true
    belongs_to :user,          optional: true
    has_many   :notifications, as: :content, dependent: :destroy

    after_create :notify_author, if: :notify_author?

    def username
      user_id ? user.display_name : name
    end

    def notify_author?
      user_id ? content.user_id != user_id : true
    end

    def notify_author
      notification = { content: self,
                       event:   :comment,
                       user_id: content.user_id }
      notification[:source_user] = user if user_id
      Elabs::Notification.create! notification
    end

    def archive!
      update(archived: true)
      notifications.destroy_all
    end
  end
end

app/models/elabs/concerns/actable_entity.rb
module Elabs
  module Concerns
    module ActableEntity
      extend ActiveSupport::Concern

      included do
        attr_accessor :update_description
        attr_reader :minor_update

        has_many :acts, as: :content, dependent: :destroy

        before_save :update_acts?
        after_save :update_acts
      end

      def minor_update=(value)
        @minor_update = ['t', '1', 1, true].include? value
      end

      def minor_update?
        @minor_update || false
      end

      private

      def update_acts? # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
        @action = if minor_update?
                    :nothing
                  elsif just_published?
                    current_publish_action
                  elsif made_locked? && act_updates?
                    current_lock_action
                  elsif notably_changed? && act_updates?
                    current_update_action
                  else
                    :nothing
                  end
      end

      def update_acts
        acts.destroy_all if %i[lock unpublish].include? @action
        reason = update_description.nil? ? nil : update_description
        Act.create content: self, event: @action, reason: reason unless @action == :nothing || hidden_in_history
      end

      # Whether or not to save the update acts for the current model
      def act_updates?
        self.class::ACT_UPDATES
      end

      def made_locked?
        changed.include?('locked') && published?
      end

      def notably_changed?
        (changed & %w[title name description short_description content excerpt]).any?
      end

      def just_published?
        changed.include?('published')
      end
    end
  end
end

app/models/elabs/concerns/content_entity.rb
module Elabs
  module Concerns
    module ContentEntity
      extend ActiveSupport::Concern

      included do
        before_save :set_publication_date

        scope :by_member,        ->(user_id) { where(user_id: user_id) }
        scope :published,        -> { where(published: true) }
        scope :unlocked,         -> { where(locked: false) }
        scope :publicly_visible, -> { published.unlocked }
        scope :for_relation,     -> { publicly_visible.order(published_at: 'desc').limit(Elabs.max_related_items) }
      end

      def locked?
        locked
      end

      def unlocked?
        !locked
      end

      def draft?
        !published
      end

      def published?
        published
      end

      def publicly_visible?
        published? && !locked?
      end

      def not_publicly_visible?
        draft? || locked?
      end

      private

      def made_publicly_visible?
        (changes_include?(:published) || changes_include?(:locked)) && published? && unlocked?
      end

      def made_publicly_invisible?
        (changes_include?(:published) && draft?) || (changes_include?(:locked) && locked? && published?)
      end

      def was_published_before?
        (changes_include?(:published) && draft?)
      end

      def set_publication_date
        self.published_at = Time.current if changed.include?('published') && published?
        self.published_at = nil if changed.include?('published') && !published?
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_publish_action
        return :nothing unless unlocked?

        published? ? :publish : :unpublish
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_lock_action
        return :nothing unless published?

        locked? ? :lock : :unlock
      end

      # method used by ActableEntity/NotifiableEntity to determine the events.
      def current_update_action
        published? && unlocked? ? :update : :nothing
      end

      def changed_by_someone_else
        changed_by.present? && changed_by.id != user.id
      end

      class_methods do
        def find_publicly_visible(slug)
          entity = where(slug: slug).published.first

          raise ActiveRecord::RecordNotFound if entity.nil?

          entity
        end
      end
    end
  end
end

app/models/elabs/concerns/countable_pivot.rb
module Elabs
  module Concerns
    module CountablePivot
      extend ActiveSupport::Concern

      # List of tables to query for update
      COUNTABLE_DEFINITION = [].freeze

      included do
        before_destroy :update_associated_counter_cache
      end

      # rubocop:disable Rails/SkipsModelValidations
      # We don't want any hook to be called
      def update_associated_counter_cache
        entity = send(self.class::COUNTABLE_DEFINITION[1])
        entity.decrement! "#{self.class::COUNTABLE_DEFINITION[0]}_count"
      end
      # rubocop:enable Rails/SkipsModelValidations
    end
  end
end

app/models/elabs/concerns/taggable.rb
module Elabs
  module Concerns
    module Taggable
      extend ActiveSupport::Concern

      included do
        attr_writer :tags_list

        after_save :save_tags_list
      end

      def save_tags_list
        if @tags_list
          tags = []
          @tags_list.split(/, */).each do |t|
            tags.push Tag.find_or_create_by(name: t.chomp)
          end

          @tags_list = nil

          update(tags: tags) if tags.count.positive?
        end

        true
      end

      # Returns a list of comma-separated tags
      def tags_list
        @tags_list || tags.map(&:name).join(', ')
      end
    end
  end
end

app/views/elabs/layouts/_content_card.html.haml
- entity_type = entity.class.table_name.singularize

- if !show_item? entity
  = render 'elabs/layouts/hidden_entry', entity: entity
- else
  %div{ class: "#{entity_type} #{entity_type}-card" }
    %header
      .header
        %h3.title{ lang: entity.language.iso639_1 }
          = content_type_icon_from_entity entity, %w[fw]
          = link_to entity.title_to_display, entity
        .subtitle= t('.by_name_html', name: link_to(entity.user.display_name, entity.user))

      %ul.information
        %li
          = icon('language', ['fw'])
          %strong= t('.language')
          = link_to entity.language.name, entity.language
        %li
          = icon('license', ['fw'])
          %strong= t('.license')
          = link_to entity.license do
            = license_icon entity.license
            = entity.license.name
        %li
          = icon('calendar-check', ['fw'])
          %strong= t('.pub_date')
          = medium_datetime entity.published_at
        %li
          = icon('info', ['fw'])
          %strong= t('.sfw')
          = boolean_icon_tag entity.sfw, 'is-sfw', 'is-nsfw'
        - if entity.respond_to? :public_projects
          %li= render 'elabs/layouts/content_classifiers_lists/projects', projects: entity.public_projects
        - if entity.respond_to? :tags
          %li= render 'elabs/layouts/content_classifiers_lists/tags', tags: entity.tags
        - if entity.respond_to? :public_albums
          %li= render 'elabs/layouts/content_classifiers_lists/albums', albums: entity.public_albums

    - if entity.short_text_to_display.present?
      %article{ lang: entity.language.iso639_1 }= render_entity_content entity, :short_text_to_display, false
    - if entity.class.name == 'Elabs::Album'
      = render 'elabs/albums/card_content', album: entity
    - if entity.class.name == 'Elabs::Upload'
      = render 'elabs/uploads/thumbnail', upload: entity

app/views/elabs/layouts/_content_download_sources.html.haml
- if Elabs.exportable_markdown
  %li.separator.download-button
    = link_to({ format: :md }, class: 'btn btn--download btn--block') do
      = icon 'download', ['fw']
      = t('.markdown_source')
  %li.download-button
    = link_to({ params: { md_format: :pandoc }, format: :md }, class: 'btn btn--download btn--block') do
      = icon 'download', ['fw']
      = t('.markdown_for_pandoc_source')

app/views/elabs/layouts/_empty.html.haml
.empty.empty--big
  .empty__title= t('.nothing_here')
  .empty__subtitle= t('.content_is_being_created')

app/views/elabs/layouts/_flash_messages.html.haml
- unless flash.empty?
  .page__messages
    - flash.each do |name, message|
      .alert{ class: "alert--#{name}" }= message

app/views/elabs/layouts/_footer.html.haml
- can_report = false if can_report.nil?

%a.fixed-link.to-top{ href: '#top' }
  = icon 'arrow-up', %w[fw 2x]

- if can_report
  %a.fixed-link.to-report{ href: '#', onclick: 'openModal(event, "report-modal")' }
    = icon 'flag', %w[fw 2x]

%footer.page__footer
  .page__footer__content
    %header
      &copy; 2018 - #{Elabs.site_name}
    .rss-links
      = icon_text('.rss', t('.rss'), ['fw'])
      = link_to t('.activity'), activities_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.albums'), albums_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.articles'), articles_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.notes'), notes_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.projects'), projects_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.uploads'), uploads_url(format: :rss, show_nsfw: show_nsfw?)
      = link_to t('.links'), links_url(format: :rss, show_nsfw: show_nsfw?)

app/views/elabs/layouts/_form_honeypot.html.haml
- if Elabs.trap_dumb_bots?
  .field{ id: "form-#{field}" }
    %label{ id: "form-#{field}-label", for: 'form-body-field' }= t('.body')
    .field-input
      %textarea{ id: "form-#{field}-field", name: 'body' }
      .field-hint= t('.robot_field_help')

  :javascript
      documentReady(function(){
        document.getElementById('form-#{field}').style.display = 'none';
        document.getElementById('form-#{field}-label').innerText= "#{t('.robot_area')}"
      })

app/views/elabs/layouts/_hidden_entry.html.haml
- if entity.locked?
  .locked.locked--large
    = icon_text 'lock', t('.content_needs_review'), ['fw']
- else
  .nsfw.nsfw--large
    = icon_text 'nsfw', t('.not_appropriate'), ['fw']

app/views/elabs/layouts/_hidden_entry_full.html.haml
- if entity.locked?
  .locked.locked--full
    .locked__title= icon_text 'lock', t('.content_needs_review'), ['fw']
    .locked__subtitle= t('.give_time_to_review')
- else
  .nsfw.nsfw--full
    .nsfw__title= icon_text 'nsfw', t('.not_appropriate'), ['fw']
    .nsfw__subtitle= t('.click_on_show_nsfw')

app/views/elabs/layouts/_hidden_entry_inline.html.haml
- if entity.locked?
  %span.locked.locked--inline
    = icon_text 'lock', t('.locked_for_review'), ['fw']
- else
  %span.nsfw.nsfw--inline
    = icon_text 'nsfw', t('.nsfw_content'), ['fw']

app/views/elabs/layouts/_language_menu.html.haml
= link_to 'English', { locale: 'en' }, lang: 'en', class: 'menu_entry'
= link_to 'Français', { locale: 'fr' }, lang: 'fr', class: 'menu_entry'

app/views/elabs/layouts/_menu.html.haml
%header.page__menu
  .page__menu__title
    = link_to Elabs.site_name, main_app.root_path, class: 'brand_link menu_entry'
    %a.menu_entry.menu_button.menu_button--for-tiny{ href: '#', onclick: 'toggleSecondaryMenu()' }= icon 'bars', ['fw']

  .page__menu__group
    = active_link_to :projects, class: 'menu_entry' do
      = icon 'cogs', %w[fw icon]
      = t('.projects')
    = active_link_to :articles, class: 'menu_entry' do
      = icon 'font', %w[fw icon]
      = t('.articles')
    = active_link_to :notes, class: 'menu_entry' do
      = icon 'sticky-note', %w[fw icon]
      = t('.notes')
    = active_link_to :albums, class: 'menu_entry' do
      = icon 'book', %w[fw icon]
      = t('.albums')
    = active_link_to :uploads, class: 'menu_entry' do
      = icon 'file', %w[fw icon]
      = t('.uploads')

    .menu_entry.dropdown
      %a{ href: '#' }
        = icon 'ellipsis-h', ['fw']
      .dropdown__menu.dropdown__menu--right
        = active_link_to :users, class: 'menu_entry' do
          = icon 'users', %w[fw icon]
          = t('.authors')
        = active_link_to :links, class: 'menu_entry' do
          = icon 'link', %w[fw icon]
          = t('.links')
        = active_link_to :tags, class: 'menu_entry' do
          = icon 'tags', %w[fw icon]
          = t('.tags')
        = active_link_to :licenses, class: 'menu_entry' do
          = icon 'license', %w[fw icon]
          = t('.licenses')
        = active_link_to :languages, class: 'menu_entry' do
          = icon 'language', %w[fw icon]
          = t('.languages')

  %a.menu_entry.menu_button.menu_button--for-small{ href: '#', onclick: 'toggleSecondaryMenu()' }= icon 'bars', ['fw']

  .page__menu__group.page__menu__group--secondary#secondary-menu
    %a.close_menu_button{ onclick: 'toggleSecondaryMenu()' }= icon 'times', %w[fw 2x]
    %a.menu_entry{ href: url_for(params: { show_nsfw: !show_nsfw? }) }
      = icon show_nsfw? ? 'eye-slash' : 'eye', %w[fw icon]
      = show_nsfw? ? t('.hide_nsfw') : t('.show_nsfw')
    .menu_entry.dropdown
      %a{ href: '#' }
        = icon 'language', ['fw']
        = t('.language')
      .dropdown__menu
        = render 'elabs/layouts/language_menu'
    - unless user_signed_in?
      = active_link_to new_user_session_path, class: 'menu_entry' do
        = icon 'sign-in-alt', %w[fw icon]
        = t('.login')
    - if user_signed_in?
      = render 'elabs/layouts/menu_member'
      - if current_user.admin?
        = render 'elabs/layouts/menu_admin'

app/views/elabs/layouts/application.html.haml
!!!
%html{ lang: locale }
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }/
    %meta{ name: 'viewport',
           content: 'width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0' }
    %meta{ 'http-equiv': 'X-UA-Compatible', content: 'ie=edge' }
    = csrf_meta_tags
    %title= page_title(@page_title)
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = auto_discovery_link_tag :rss, albums_url(format: :rss, show_nsfw: show_nsfw?)
    = auto_discovery_link_tag :rss, articles_url(format: :rss, show_nsfw: show_nsfw?)
    = auto_discovery_link_tag :rss, notes_url(format: :rss, show_nsfw: show_nsfw?)
    = auto_discovery_link_tag :rss, projects_url(format: :rss, show_nsfw: show_nsfw?)
    = auto_discovery_link_tag :rss, uploads_url(format: :rss, show_nsfw: show_nsfw?)
  %body.page#top
    = render 'elabs/layouts/menu'

    .page__wrapper

      %noscript
        .alert.alert--warning
          = t('.disabled_js')

      = render 'elabs/layouts/announcements'

      .page__header

        - if @page_title # This variable should be set in views (or controllers)
          %h1.page__header__title= @page_title

        - if render_filters?
          .page__header__actions
            %a.page__header__actions_button{ href: '#' }
              = icon 'filter', ['fw']
            = render "elabs/#{controller_name}/filters"

      = render 'elabs/layouts/flash_messages'

      .page__content
        .page__content__container
          = yield

    .modal#report-modal
      .modal__overlay{ onclick: 'closeModal("report-modal")' }
      .modal__window
        .modal__window__title
          %h1= t('.report_this_page')
          .modal__close-button
            %i.fa.fa-times{ onclick: 'closeModal("report-modal")' }
        .modal__window__content
          = render 'elabs/reports/form', new_report: @new_report

    = render 'elabs/layouts/footer', can_report: true

  -# Widget templates
  = render 'elabs/layouts/shortcodes/widgets/vue/all_widgets'